apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cic-search.fullname" . }}-tika-fakecache
  labels:
    {{ include "cic-search.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.tika-fakecache.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cic-search.name" . }}-tika-fakecache
  template:
    metadata:
      labels:
        app: {{ include "cic-search.name" . }}-tika-fakecache
    spec:
      containers:
      - name: tika-fakecache
        image: "{{ .Values.tika-fakecache.image.repository }}:{{ .Values.tika-fakecache.image.tag }}" 
        ports:
        # Define ports here based on the service's requirements
        env:
        # Define environment variables here based on the service's requirements
        volumeMounts:
        # Define volume mounts here based on the service's requirements
      volumes:
      # Define volumes here based on the service's requirements
