apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cic-search.fullname" . }-tika}
  labels:
    {{- include "cic-search.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.tika.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cic-search.name" . }-tika}
  template:
    metadata:
      labels:
        app: {{ include "cic-search.name" . }-tika}
    spec:
      containers:
      - name: tika
        image: "{{ .Values.tika.image.repository }}:{{ .Values.tika.image.tag }}" 
        ports:
        # Define ports here based on the service's requirements
        env:
        # Define environment variables here based on the service's requirements
        volumeMounts:
        # Define volume mounts here based on the service's requirements
      volumes:
      # Define volumes here based on the service's requirements
