apiVersion: v1
kind: Secret
metadata:
  annotations:
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
  labels:
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  name: {{ .Values.secret.secretName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secret.dockerconfigjson | b64enc | quote }}
