apiVersion: v1
kind: Service
metadata:
  name: {{ include "cicero-frontend.fullname" . }}
  labels:
    {{- include "cicero-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - appProtocol: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: port-{{ .Values.service.port }}
  selector:
    {{- include "cicero-frontend.selectorLabels" . | nindent 4 }}
