apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-semantic-search.fullname" . }-spacy-services}
  labels:
    {{- include "open-semantic-search.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.spacy-services.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "open-semantic-search.name" . }-spacy-services}
  template:
    metadata:
      labels:
        app: {{ include "open-semantic-search.name" . }-spacy-services}
    spec:
      containers:
      - name: spacy-services
        image: "{{ .Values.spacy-services.image.repository }}:{{ .Values.spacy-services.image.tag }}" 
        ports:
        # Define ports here based on the service's requirements
        env:
        # Define environment variables here based on the service's requirements
        volumeMounts:
        # Define volume mounts here based on the service's requirements
      volumes:
      # Define volumes here based on the service's requirements
