apiVersion: v1
kind: Service
metadata:
  name: {{ include "cic-backend.fullname" . }}
  labels:
    {{- include "cic-backend.labels" . | nindent 4 }}
spec:
  {{- range .Values.service }}
  type: {{ .type }}
  ports:
  - appProtocol: {{ .appProtocol }}
    port: {{ .port }}
    targetPort: {{ .port }}
    protocol: {{ .protocol }}
    name: port-{{ .port }}
  {{- end }}
  selector:
    {{- include "cic-backend.selectorLabels" . | nindent 4 }}
